import React from 'react';
import AboutSection from './components/About';



export const metadata = {
  title: "Reshan - About",
  description: "Generated by create next app",
};

function page() {
  
  return (
    <>
     <AboutSection /> 
    </>
  )
}

export default page
