import React from 'react'

export const metadata = {
  title: "Reshan - Contact Us",
  description: "Generated by create next app",
};


function page() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-between p-24">
      Contact
    </div>
  )
}

export default page
