import React from 'react';

export const metadata = {
  title: "Reshan - Contact Us",
  description: "Generated by create next app",
};

function page() {
  return (
    <div className="text-black flex min-h-screen flex-col items-center justify-center p-20">
      <h2 className="text-center text-3xl font-bold mb-8 md:mb-12">Contact Us</h2>
      <div className="flex flex-col items-center space-y-4">
        <div className="flex items-center space-x-3">
          <a
            href="mailto:example@example.org"
            className="text-xl text-primary-600 hover:underline"
          >
            example@example.org
          </a>
        </div>
        <p className="text-gray-600">Feel free to reach out to us for any inquiries.</p>
      </div>
    </div>
  );
}

export default page;
