import React from 'react'


export const metadata = {
  title: "Reshan - About",
  description: "Generated by create next app",
};

function About() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-between p-24">
      about
    </div>
  )
}

export default About;
