import React from 'react';
import ProjectsSection from "../../components/Projects/ProjectsSection";



export const metadata = {
  title: "Reshan - Projects",
  description: "Generated by create next app",
};

function Projects() {
  return (
      <div className="flex min-h-screen flex-col items-center justify-between p-24">
        <ProjectsSection />
      </div>
  )
}

export default Projects;
