import HeroSection from "./components/HomePage/HeroSection";
import AchievementsSection from "./components/HomePage/AchievementsSection";
import LatestProjects from "./components/LatestProjects/LatestProjects";


export const metadata = {
  title: 'Reshan - HomePage',
  description: 'Generated by create next app',
}


export default function Home() {
  return (
      <div className="container mt-16 mx-auto">
        <HeroSection />
        {/* <AchievementsSection /> */}
        <LatestProjects />
      </div>
  );
}
