import React from 'react';
import ProjectsSection from '../components/Sculptures/ProjectsSection';

export const metadata = {
  title: "Reshan - Projects",
  description: "Generated by create next app",
};


function page() {
  return (
    <div>
      <ProjectsSection />
    </div>
  )
}

export default page
